### ISSUE TITLE
Logging breaks when using nuget and configuration from the readme.

### ISSUE THREAD

**Issue by mazk0** [cdon-dev/CMP.ServiceFabric.Logging#1]
When usning CMP.Logging nuget the logging breaks. Dependency logging is still logged from CMP.SupportType.

Event and Reques logging are missing most of the Custom Properties.

Trace logging of CMP.GatewayType.

**Comment by perokvist** [comment]
Was this by using the extensions on the ServiceFabric context ?
Please compare your case before and after introducing this package.

**Comment by perokvist** [comment]
```
context =>
{
var telemetryConfiguration = TelemetryConfiguration.CreateFromConfiguration(config["ApplicationInsights:InstrumentationKey"]);
var logger = context.ConfigureLogging(telemetryConfiguration, environment);
return new Foo(context, config);
}).GetAwaiter().GetResult();
```

**Comment by perokvist** [comment]
verify using 0.1.1-alpha

**Comment by mazk0** [comment]
Solved the issue by reverting to the same older nuget packages used by the Catalog team.
